// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server;

namespace Server.Migrations
{
    [DbContext(typeof(SmartShareContext))]
    [Migration("20190208194550_Final")]
    partial class Final
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Server.SmartShareFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Created")
                        .HasColumnName("created");

                    b.Property<int>("DownloadCount")
                        .HasColumnName("download_count");

                    b.Property<string>("Expiration")
                        .HasColumnName("expiration");

                    b.Property<byte[]>("FileData")
                        .HasColumnName("file_data");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnName("file_name");

                    b.Property<int>("MaximumDownloads")
                        .HasColumnName("maximum_downloads");

                    b.Property<string>("Password")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.ToTable("smart_share_file");
                });
#pragma warning restore 612, 618
        }
    }
}
